### ISSUE TITLE
gwnn_model,exp_results

### ISSUE THREAD

**Issue by ohhhh2022** [zhengdaoli/AGC-net#1]
作者您好，很荣幸能够读到您的论文，有个问题想请教您，在运行代码时显示gwnn_model,exp_results这两个模块不存在。是否代码上传遗漏了呢？

**Comment by zhengdaoli** [comment]
这两个模块直接删掉就行了，不需要了。

**Comment by ohhhh2022** [comment]
好的，已解决，谢谢。
